# -*- coding: utf-8 -*-
"""model-kardiomegaly-testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ax4K2M6YrQiptQ412l6d6fdk-JPhm_39

**KODE UNTUK MENGHAPUS FOTO YANG TIDAK ADA DI METADATA.**

**MENGHAPUS FOTO AGAR SESUAI DENGAN YANG ADA DI METADATA**
"""

import os
import pandas as pd

# ==========================================
# 1. KONFIGURASI PATH
# ==========================================
PATH_CSV = "/content/drive/MyDrive/Semester 4/Penambangan Data/proyek_kardiomegali/metadata/metadata_pasien_penambangan_data_rsj - Sheet1.csv"
DIR_RAW_INTERNAL = "/content/drive/MyDrive/Semester 4/Penambangan Data/proyek_kardiomegali/data/raw/internal_rsj"

# KONTROL EKSEKUSI
# Ubah ke True untuk langsung menghapus berkas fisik agar jumlahnya sama dengan metadata
HAPUS_FISIK = True

# ==========================================
# 2. EKSTRAKSI NAMA DARI METADATA
# ==========================================
df = pd.read_csv(PATH_CSV)
df.dropna(subset=['nama_file_gambar'], inplace=True)

# Kumpulkan semua nama dasar dari metadata (tanpa spasi di ujung)
nama_di_metadata = set(df['nama_file_gambar'].str.strip().tolist())

# ==========================================
# 3. IDENTIFIKASI FILE LIAR DI FOLDER RAW
# ==========================================
all_files_in_raw = os.listdir(DIR_RAW_INTERNAL)
PROBABLE_EXTENSIONS = ['.png', '.jpg', '.jpeg', '.bmp', '.PNG', '.JPG', '.JPEG', '.BMP']
files_to_delete = []

for file_name in all_files_in_raw:
    # Abaikan jika itu folder internal
    if os.path.isdir(os.path.join(DIR_RAW_INTERNAL, file_name)):
        continue

    # Ambil nama dasar file dengan memotong ekstensinya jika ada
    base_name = file_name
    for ext in PROBABLE_EXTENSIONS:
        if file_name.lower().endswith(ext.lower()):
            base_name = file_name[:-len(ext)]
            break

    base_name = base_name.strip()

    # Jika nama file utuh maupun nama dasarnya tidak terdaftar di gsheets, tandai hapus
    if (file_name not in nama_di_metadata) and (base_name not in nama_di_metadata):
        files_to_delete.append(file_name)

# ==========================================
# 4. EKSEKUSI PEMBERSIHAN DATA
# ==========================================
print("--- LAPORAN SINKRONISASI DATA ---")
print(f"Jumlah baris valid di Metadata (GSheets) : {len(nama_di_metadata)}")
print(f"Jumlah total file awal di folder raw     : {len(all_files_in_raw)}")
print(f"Jumlah file tidak terdaftar (liar)       : {len(files_to_delete)}")
print("-" * 50)

if len(files_to_delete) > 0:
    if HAPUS_FISIK:
        terhapus = 0
        for f in files_to_delete:
            try:
                os.remove(os.path.join(DIR_RAW_INTERNAL, f))
                terhapus += 1
            except Exception as e:
                print(f"Gagal menghapus {f}: {e}")
        print(f"✅ SUKSES: {terhapus} file liar telah dihapus permanen dari folder raw.")
        print(f"Jumlah file di folder internal_rsj sekarang: {len(os.listdir(DIR_RAW_INTERNAL))}")
    else:
        print("ℹ️ MODE AMAN: Mengganti HAPUS_FISIK = True untuk mulai membersihkan.")
else:
    print("✅ SINKRON: Folder raw sudah bersih dan jumlahnya sesuai dengan metadata rekam medis!")

"""**DIBAWAH INI PERINTAH UNTUK MEMBUAT DATA TRAINING**"""

import os
import cv2
import pandas as pd
from sklearn.model_selection import train_test_split

# ==========================================
# 1. KONFIGURASI PATH & PARAMETER
# ==========================================
PATH_CSV = "/content/drive/MyDrive/Semester 4/Penambangan Data/proyek_kardiomegali/metadata/metadata_pasien_penambangan_data_rsj - Sheet1.csv"
DIR_RAW_INTERNAL = "/content/drive/MyDrive/Semester 4/Penambangan Data/proyek_kardiomegali/data/raw/internal_rsj"
DIR_RAW_KAGGLE = "/content/drive/MyDrive/Semester 4/Penambangan Data/proyek_kardiomegali/data/raw/kaggle_source"
DIR_OUTPUT = "/content/drive/MyDrive/Semester 4/Penambangan Data/proyek_kardiomegali/data/dataset_split"

TARGET_SIZE = (128, 128)
VAL_SIZE = 0.2
RANDOM_STATE = 42

for split in ['train', 'val']:
    for kelas in ['0_normal', '1_kardiomegali']:
        os.makedirs(os.path.join(DIR_OUTPUT, split, kelas), exist_ok=True)

# ==========================================
# 2. PROSES DATA INTERNAL (RSJ) -> PAKSA KE .PNG
# ==========================================
print("Mengompresi dan membagi data Internal RSJ...")
df = pd.read_csv(PATH_CSV)
df.dropna(subset=['label_kardiomegali'], inplace=True)
df['label_kardiomegali'] = df['label_kardiomegali'].astype(int)

train_df, val_df = train_test_split(
    df, test_size=VAL_SIZE, stratify=df['label_kardiomegali'], random_state=RANDOM_STATE
)

def process_and_save(dataframe, split_name):
    PROBABLE_EXTENSIONS = ['.png', '.jpg', '.jpeg', '.bmp', '.PNG', '.JPG', '.JPEG', '.BMP']

    for _, row in dataframe.iterrows():
        nama_file_dasar = str(row['nama_file_gambar']).strip()
        label = row['label_kardiomegali']
        sub_folder = "1_kardiomegali" if label == 1 else "0_normal"

        file_ditemukan = False
        path_asal = ""

        for ext in PROBABLE_EXTENSIONS:
            if nama_file_dasar.lower().endswith(ext.lower()):
                test_path = os.path.join(DIR_RAW_INTERNAL, nama_file_dasar)
            else:
                test_path = os.path.join(DIR_RAW_INTERNAL, f"{nama_file_dasar}{ext}")

            if os.path.exists(test_path):
                path_asal = test_path
                file_ditemukan = True
                break

        if file_ditemukan:
            # Hilangkan ekstensi lama jika ada di string nama_file_dasar
            nama_clean = nama_file_dasar
            for ext in PROBABLE_EXTENSIONS:
                if nama_clean.lower().endswith(ext.lower()):
                    nama_clean = nama_clean[:-len(ext)]
                    break

            # Paksa keluaran akhir menjadi berkstensi .png
            nama_file_final = f"{nama_clean.strip()}.png"
            path_tujuan = os.path.join(DIR_OUTPUT, split_name, sub_folder, nama_file_final)

            img = cv2.imread(path_asal, cv2.IMREAD_GRAYSCALE)
            if img is not None:
                img_resized = cv2.resize(img, TARGET_SIZE, interpolation=cv2.INTER_AREA)
                cv2.imwrite(path_tujuan, img_resized)
            else:
                print(f"Gagal membaca gambar: {path_asal}")
        else:
            print(f"Peringatan: File '{nama_file_dasar}' tidak ditemukan.")

process_and_save(train_df, 'train')
process_and_save(val_df, 'val')

# ==========================================
# 3. PROSES & PEMBAGIAN DATA KAGGLE
# ==========================================
print("Memproses dan membagi data Kaggle...")
all_kaggle_files = [f for f in os.listdir(DIR_RAW_KAGGLE) if f.endswith(('.png', '.jpg', '.jpeg'))]

kaggle_train, kaggle_val = train_test_split(
    all_kaggle_files, test_size=VAL_SIZE, random_state=RANDOM_STATE
)

def process_kaggle_files(file_list, split_name):
    for nama_file in file_list:
        path_asal = os.path.join(DIR_RAW_KAGGLE, nama_file)
        path_tujuan = os.path.join(DIR_OUTPUT, split_name, "1_kardiomegali", f"kaggle_{nama_file}")
        if os.path.exists(path_asal):
            img = cv2.imread(path_asal, cv2.IMREAD_GRAYSCALE)
            img_resized = cv2.resize(img, TARGET_SIZE, interpolation=cv2.INTER_LINEAR)
            cv2.imwrite(path_tujuan, img_resized)

process_kaggle_files(kaggle_train, 'train')
process_kaggle_files(kaggle_val, 'val')

print("\n🎉 Preprocessing selesai! Semua citra telah diselaraskan ke 128x128 dan siap ditraining.")

"""**Dibawah ini adalah perintah untuk Data Loader**"""

import tensorflow as tf
import os

# ==========================================
# 1. KONFIGURASI PARAMETER DATASET
# ==========================================
# Path menuju folder hasil split data yang sudah bersih
DIR_DATASET = "/content/drive/MyDrive/Semester 4/Penambangan Data/proyek_kardiomegali/data/dataset_split"
IMG_SIZE = (128, 128)
BATCH_SIZE = 32

print("--- Memuat Dataset Training ---")
train_ds = tf.keras.utils.image_dataset_from_directory(
    os.path.join(DIR_DATASET, 'train'),
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    color_mode='grayscale', # Memaksa gambar dibaca dalam 1 channel (Hitam-Putih) untuk hemat RAM
    label_mode='binary',    # Label otomatis biner: 0 untuk normal, 1 untuk kardiomegali
    shuffle=True,           # Diacak agar distribusi data internal RSJ dan Kaggle merata
    seed=42
)

print("\n--- Memuat Dataset Validasi ---")
val_ds = tf.keras.utils.image_dataset_from_directory(
    os.path.join(DIR_DATASET, 'val'),
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    color_mode='grayscale',
    label_mode='binary',
    shuffle=False           # Validasi tidak perlu diacak agar hasil evaluasi urut dan konsisten
)

# ==========================================
# 2. OPTIMASI PARALELISASI & MEMORI (TURBO)
# ==========================================
# Mempercepat loading gambar dari Google Drive ke RAM GPU secara otomatis
AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.cache().prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

print("\n✅ Data Loader siap! Data berhasil dimuat di memori dan dioptimasi.")

"""**DIBAWAH INI ADALAH PERINTAH UNTUK MEMBUAT MODEL**

Arsitektur Model CNN & Kompilasi
"""

from tensorflow.keras import layers, models

# ==========================================
# 1. MEMBANGUN MODEL CNN
# ==========================================
model = models.Sequential([
    # Rescaling piksel ke rentang 0-1
    layers.Rescaling(1./255, input_shape=(128, 128, 1)),

    # Blok 1: Deteksi fitur dasar (tepi dan garis)
    layers.Conv2D(32, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    # Blok 2: Deteksi fitur tekstur dan bentuk jantung
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    # Blok 3: Fitur morfometri yang lebih kompleks
    layers.Conv2D(128, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    # Flatten & Dense Layer
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5), # Mencegah ketergantungan berlebih pada data Kaggle (Overfitting)

    # Output Layer (Binary Classification via Sigmoid)
    layers.Dense(1, activation='sigmoid')
])

# Kompilasi dengan metrik medis: Recall sangat penting untuk screening agar tidak "miss" pasien sakit
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy', tf.keras.metrics.Recall(name='recall'), tf.keras.metrics.Precision(name='precision')]
)

model.summary()

"""**Training Model & Callback**

Kita akan memasang "rem otomatis" agar model berhenti berlatih jika akurasi sudah tidak naik lagi, serta menyimpan hasil terbaik secara otomatis ke Drive.
"""

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

# Tentukan path penyimpanan model terbaik di Drive Anda
PATH_MODEL_BEST = "/content/drive/MyDrive/Semester 4/Penambangan Data/proyek_kardiomegali/models/cnn_kardiomegali_best.h5"

# Simpan model hanya jika performa validasi (val_loss) membaik
save_callback = ModelCheckpoint(filepath=PATH_MODEL_BEST, monitor='val_loss', save_best_only=True, verbose=1)

# Berhenti otomatis jika dalam 5 epoch tidak ada perbaikan
stop_callback = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

print("--- Memulai Pelatihan Model ---")
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=25,
    callbacks=[save_callback, stop_callback]
)

"""**Evaluasi & Laporan Diagnostik**

Setelah selesai, kita perlu melihat seberapa akurat model dalam membedakan Kardiomegali vs Normal.
"""

import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

# Ambil gambar dan label asli dari validation set
y_true = []
y_pred_prob = []

for images, labels in val_ds:
    y_true.extend(labels.numpy())
    preds = model.predict(images)
    y_pred_prob.extend(preds)

# Terapkan Threshold 0.5 sesuai spesifikasi Anda
y_pred = [1 if prob >= 0.5 else 0 for prob in y_pred_prob]

print("\n--- HASIL EVALUASI MODEL ---")
print(classification_report(y_true, y_pred, target_names=['Normal', 'Kardiomegali']))

"""**Fungsi Grad-CAM untuk Backend Penjelas**"""

import numpy as np
import tensorflow as tf
import cv2
import matplotlib.pyplot as plt

def make_gradcam_heatmap(img_array, model, last_conv_layer_name, pred_index=None):
    # 1. Buat model baru yang memetakan citra input ke aktivasi layer konvolusi terakhir & output prediksi
    grad_model = tf.keras.models.Model(
        inputs=[model.inputs],
        outputs=[model.get_layer(last_conv_layer_name).output, model.output]
    )

    # 2. Hitung gradien dari top kelas prediksi terhadap aktivasi layer konvolusi terakhir
    with tf.GradientTape() as tape:
        last_conv_layer_output, preds = grad_model(img_array)
        if pred_index is None:
            pred_index = tf.argmax(preds[0])
        class_channel = preds[:, pred_index]

    # 3. Ini adalah gradien dari kelas keluaran terhadap fungsionalitas layer konvolusi terakhir
    grads = tape.gradient(class_channel, last_conv_layer_output)

    # 4. Ambil rata-rata gradien secara spasial (global average pooling)
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))

    # 5. Kalikan setiap saluran di feature map dengan "seberapa penting saluran ini" terhadap kelas target
    last_conv_layer_output = last_conv_layer_output[0]
    heatmap = last_conv_layer_output @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)

    # 6. Normalisasi heatmap antara 0 dan 1 untuk visualisasi, lalu terapkan ReLU
    heatmap = tf.maximum(heatmap, 0) / tf.reduce_max(heatmap)
    return heatmap.numpy()

def save_and_display_gradcam(img_path, heatmap, cam_path="cam.png", alpha=0.4):
    # Muat gambar asli
    img = cv2.imread(img_path)

    # Rescale heatmap ke ukuran gambar asli (misal kembali ke ukuran asli RSJ yang besar)
    heatmap = cv2.resize(heatmap, (img.shape[1], img.shape[0]))

    # Ubah heatmap menjadi rentang 0-255
    heatmap = np.uint8(255 * heatmap)

    # Gunakan skema warna JET untuk memberikan warna map panas (merah = panas/tinggi)
    heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)

    # Gabungkan (overlay) heatmap dengan gambar rontgen asli menggunakan transparansi alpha
    superimposed_img = heatmap * alpha + img
    superimposed_img = np.clip(superimposed_img, 0, 255).astype(np.uint8)

    # Simpan hasil visualisasi
    cv2.imwrite(cam_path, superimposed_img)
    return cam_path

"""**Visualisasi Grafik Akurasi dan Loss Model**"""

import matplotlib.pyplot as plt

# ==========================================
# VISUALISASI GRAFIK EVALUASI TRAINING
# ==========================================

# 1. Membuat Figure dengan 2 Subplot (Kiri: Akurasi, Kanan: Loss)
plt.figure(figsize=(14, 5))

# Subplot 1: Akurasi
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], marker='o', label='Train Accuracy', color='#005088')
plt.plot(history.history['val_accuracy'], marker='s', label='Val Accuracy', color='#11caa0')
plt.title('Model Accuracy History', fontsize=14, fontweight='bold', pad=10)
plt.xlabel('Epoch', fontsize=12)
plt.ylabel('Accuracy', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(loc='lower right', fontsize=11)

# Subplot 2: Loss
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], marker='o', label='Train Loss', color='#e056fd')
plt.plot(history.history['val_loss'], marker='s', label='Val Loss', color='#ff7675')
plt.title('Model Loss History', fontsize=14, fontweight='bold', pad=10)
plt.xlabel('Epoch', fontsize=12)
plt.ylabel('Loss', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(loc='upper right', fontsize=11)

# Mengatur tata letak agar tidak saling bertabrakan
plt.tight_layout()

# Simpan grafik otomatis ke Drive untuk keperluan aset laporan/papper
PATH_GRAFIK = "/content/drive/MyDrive/Semester 4/Penambangan Data/proyek_kardiomegali/models/grafik_evaluasi_cnn.png"
plt.savefig(PATH_GRAFIK, dpi=300)
print(f"✅ Grafik evaluasi berhasil disimpan di: {PATH_GRAFIK}")

# Tampilkan Grafik di Google Colab
plt.show()